name: Merge Queue

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  check-merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Show PR Labels
        run: |
          echo "PR Labels:"
          echo '${{ toJson(github.event.pull_request.labels) }}'

      - name: Check if PR has 'Merge pull request' label
        run: |
          LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}' | grep -o '"name": *"Merge pull request"' || true)
          if [[ -z "$LABELS" ]]; then
            echo "PR does not have 'Merge pull request' label. Exiting."
            exit 1
          fi

  validate-branch:
    needs: check-merge-queue
    runs-on: ubuntu-latest
    if: contains(fromJson('["main", "develop"]'), github.event.pull_request.base.ref)
    steps:
      - name: Run tests and approvals
        run: |
          echo "Running validation checks..."
          # Add actual CI/CD checks here
          echo "Validation passed."

  merge-pr:
    needs: validate-branch
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
