name: Enforce Merge Queue for Specific PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce-merge-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        id: check-title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ ^xxx ]]; then
            echo "ALLOW_MERGE_QUEUE=true" >> $GITHUB_ENV
          else
            echo "ALLOW_MERGE_QUEUE=false" >> $GITHUB_ENV
          fi
          
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures a git repository exists

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add PR to Merge Queue (If Allowed)
        if: env.ALLOW_MERGE_QUEUE == 'true'
        run: |
          gh pr merge --merge --auto ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Block Merge (If Not Allowed)
        if: env.ALLOW_MERGE_QUEUE == 'false'
        run: |
          echo "This PR does not follow the naming convention (xxx). Please merge manually."
          exit 1
